2020-07-12 22:28:27,419 INFO: errors [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py:450]
2020-07-12 22:30:57,855 INFO: errors [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py:450]
2020-07-12 22:30:58,150 INFO: errors [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py:450]
2020-07-12 22:31:12,134 ERROR: Exception on /venues/create [GET] [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py", line 152, in create_venue_form
    form = VenueForm()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 141, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-07-12 22:31:14,866 ERROR: Exception on /artists/create [GET] [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py", line 339, in create_artist_form
    form = ArtistForm()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 141, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-07-12 22:31:22,982 ERROR: Exception on /shows/create [GET] [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py", line 407, in create_shows
    form = ShowForm()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 141, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-07-12 22:32:48,655 INFO: errors [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py:450]
2020-07-12 22:33:01,592 ERROR: Exception on /venues/create [GET] [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py", line 152, in create_venue_form
    form = VenueForm()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 141, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-07-12 22:33:03,455 ERROR: Exception on /shows/create [GET] [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py", line 407, in create_shows
    form = ShowForm()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 141, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-07-12 22:33:15,010 INFO: errors [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py:450]
2020-07-12 22:33:15,277 INFO: errors [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py:450]
2020-07-12 22:33:21,859 INFO: errors [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py:450]
2020-07-12 22:33:31,235 ERROR: Exception on /artists/create [GET] [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py", line 339, in create_artist_form
    form = ArtistForm()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 141, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-07-12 22:34:27,610 INFO: errors [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py:452]
2020-07-12 22:34:35,106 INFO: errors [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py:452]
2020-07-12 22:34:41,094 ERROR: Exception on /venues/create [GET] [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py", line 154, in create_venue_form
    form = VenueForm()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 141, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-07-12 22:35:11,417 INFO: errors [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py:452]
2020-07-12 22:35:11,677 INFO: errors [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py:452]
2020-07-12 22:35:15,845 ERROR: Exception on /venues/create [GET] [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py", line 154, in create_venue_form
    form = VenueForm()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 141, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-07-12 22:35:18,546 ERROR: Exception on /venues/create [GET] [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py", line 154, in create_venue_form
    form = VenueForm()
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/form.py", line 131, in process
    field.process(formdata)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 141, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "/Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/env/lib/python3.7/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-07-12 22:35:36,854 INFO: errors [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py:452]
2020-07-12 22:36:37,754 INFO: errors [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py:452]
2020-07-12 22:36:43,865 INFO: errors [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py:452]
2020-07-12 22:36:56,912 INFO: errors [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py:452]
2020-07-12 22:37:59,254 INFO: errors [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py:452]
2020-07-12 22:40:09,216 INFO: errors [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py:452]
2020-07-12 22:40:16,437 INFO: errors [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py:452]
2020-07-12 22:40:24,889 INFO: errors [in /Users/amasics/Documents/Full_Stack_Web_Dev/Fresh-Fyyur/backend/app.py:452]
